# Generated by Django 5.0.6 on 2024-06-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("react", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="streamlink",
            name="link",
        ),
        migrations.AlterField(
            model_name="streamlink",
            name="slug",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
