# Generated by Django 5.0.6 on 2024-06-18 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("react", "0002_remove_streamlink_link_alter_streamlink_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="EachStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("account", models.IntegerField()),
                ("link", models.CharField(blank=True, max_length=100)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="react.streamlink",
                    ),
                ),
            ],
        ),
    ]
