# Generated by Django 5.0.6 on 2024-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("react", "0004_streamlink_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eachstream",
            name="link",
            field=models.URLField(),
        ),
    ]
