# Generated by Django 5.0.6 on 2024-06-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("react", "0009_eachstream_is_edited_alter_eachstream_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="streamlink",
            name="status",
        ),
    ]
