# Generated by Django 5.0.6 on 2024-06-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("react", "0010_remove_streamlink_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamlink",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
