# Generated by Django 5.0.6 on 2024-07-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("react", "0012_remove_streamlink_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="eachstream",
            name="count",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
