# Generated by Django 5.2.5 on 2025-08-19 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("react", "0014_usertoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="LockFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder_id", models.CharField(max_length=30)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
