# Generated by Django 5.2.5 on 2025-08-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("react", "0015_lockfolder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lockfolder",
            name="folder_id",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
