# Generated by Django 5.2.5 on 2025-08-20 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("react", "0016_alter_lockfolder_folder_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertoken",
            name="page",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ShareFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("folder_id", models.CharField(max_length=30)),
                (
                    "key",
                    models.CharField(
                        default="L6hjfGr3Ii4jgw6qzQ447ayWclQbrH",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="react.usertoken",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="7UmFcXNA551M6OpLjmwJi1tMihgUFw",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("device_info", models.TextField(blank=True, null=True)),
                ("browser_info", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_used", models.DateTimeField(default=django.utils.timezone.now)),
                ("page", models.TextField(blank=True, null=True)),
                (
                    "share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="react.sharefolder",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="sharefolder",
            constraint=models.UniqueConstraint(
                fields=("folder_id", "session"), name="unique_folder_per_session"
            ),
        ),
    ]
