# Generated by Django 5.2.5 on 2025-08-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("react", "0017_usertoken_page_sharefolder_accessfolder_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessfolder",
            name="key",
        ),
        migrations.RemoveField(
            model_name="sharefolder",
            name="key",
        ),
        migrations.AddField(
            model_name="accessfolder",
            name="link",
            field=models.CharField(
                default="yGFyVJBtjuaCdO2LTRcEXljJbwNIm7", max_length=50, unique=True
            ),
        ),
        migrations.AddField(
            model_name="sharefolder",
            name="link",
            field=models.CharField(
                default="d1PW9OutrTZorTIRSCNLcC7aGUOIvW", max_length=50, unique=True
            ),
        ),
    ]
