# Generated by Django 5.0.4 on 2024-05-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_movierulz_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="IBomma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("image", models.URLField()),
                ("link", models.URLField()),
            ],
        ),
    ]
