# Generated by Django 5.0.4 on 2024-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_ibomma"),
    ]

    operations = [
        migrations.CreateModel(
            name="FCM_token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=500)),
            ],
        ),
    ]
