# Generated by Django 5.0.4 on 2024-05-05 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_fcm_token_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcm_token",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
